import traceback
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

import cv2
import numpy as np

from src.detection.face_detection import FaceDetector
from src.detection.eye_tracking import EyeTracker
from src.detection.mouth_detection import MouthMonitor
from src.detection.multi_face import MultiFaceDetector
from src.detection.object_detection import ObjectDetector


class ProctoringEvent:
    """
    Normalized event generated by the detection engine.

    This class intentionally keeps the detection engine independent
    from FastAPI/database/WebSocket implementation details.
    """

    def __init__(
        self,
        session_id: str,
        timestamp: str,
        event_type: str,
        severity: str,
        confidence: float,
        message: str,
        metadata: Optional[Dict[str, Any]] = None,
    ):
        self.session_id = session_id
        self.timestamp = timestamp
        self.event_type = event_type
        self.severity = severity
        self.confidence = float(confidence)
        self.message = message
        self.metadata = metadata or {}

    def to_dict(self) -> Dict[str, Any]:
        """Convert the event into a JSON-serializable dictionary."""
        return {
            "session_id": self.session_id,
            "timestamp": self.timestamp,
            "event_type": self.event_type,
            "severity": self.severity,
            "confidence": self.confidence,
            "message": self.message,
            "metadata": self.metadata,
        }


class DetectionAdapter:
    """
    Adapter between the FastAPI proctoring service and the existing
    exam-detection engine.

    The adapter does NOT implement detection algorithms itself.
    It only calls the existing detectors and converts their results
    into normalized ProctoringEvent objects.
    """

    def __init__(self, config: Any, session_id: str):
        self.config = config
        self.session_id = session_id

        # Initialize the existing detection modules.
        self.face_detector = FaceDetector(config)
        self.eye_tracker = EyeTracker(config)
        self.mouth_monitor = MouthMonitor(config)
        self.multi_face_detector = MultiFaceDetector(config)
        self.object_detector = ObjectDetector(config)

        self._closed = False

    def process_frame(self, frame: np.ndarray) -> List[ProctoringEvent]:
        """
        Process a single OpenCV frame.

        Parameters
        ----------
        frame:
            BGR NumPy image received from the browser/backend.

        Returns
        -------
        List[ProctoringEvent]
            Normalized proctoring events generated from this frame.
        """

        events: List[ProctoringEvent] = []

        try:
            if self._closed:
                return events

            # Basic frame validation.
            if frame is None:
                return events

            if not isinstance(frame, np.ndarray):
                raise TypeError(
                    f"Expected numpy.ndarray, got {type(frame).__name__}"
                )

            if frame.size == 0:
                return events

            timestamp = datetime.now(timezone.utc).isoformat()

            # ---------------------------------------------------------
            # 1. FACE DETECTION
            # ---------------------------------------------------------

            face_present = self.face_detector.detect_face(frame)

            if not face_present:
                events.append(
                    ProctoringEvent(
                        session_id=self.session_id,
                        timestamp=timestamp,
                        event_type="FACE_DISAPPEARED",
                        severity="high",
                        confidence=1.0,
                        message="Face not detected",
                    )
                )

            # ---------------------------------------------------------
            # 2. MULTIPLE FACE DETECTION
            # ---------------------------------------------------------

            try:
                multi_face_result = self.multi_face_detector.detect_faces(frame)

                if multi_face_result is not None:
                    multiple_faces = False
                    face_count = 0

                    if isinstance(multi_face_result, int):
                        face_count = multi_face_result
                        multiple_faces = face_count > 1

                    elif isinstance(multi_face_result, (list, tuple)):
                        face_count = len(multi_face_result)
                        multiple_faces = face_count > 1

                    elif isinstance(multi_face_result, bool):
                        multiple_faces = multi_face_result

                    if multiple_faces:
                        events.append(
                            ProctoringEvent(
                                session_id=self.session_id,
                                timestamp=timestamp,
                                event_type="MULTIPLE_FACES",
                                severity="critical",
                                confidence=1.0,
                                message="Multiple faces detected",
                                metadata={
                                    "face_count": face_count,
                                },
                            )
                        )

            except AttributeError:
                # Some versions of the detector may expose a different
                # method name. Do not crash the entire proctoring pipeline.
                pass

            # ---------------------------------------------------------
            # 3. EYE / GAZE TRACKING
            # ---------------------------------------------------------

            try:
                eye_result = self.eye_tracker.process(frame)

                if eye_result is not None:
                    if isinstance(eye_result, dict):
                        gaze_direction = eye_result.get("gaze_direction")
                        looking_away = eye_result.get("looking_away", False)
                        confidence = eye_result.get("confidence", 1.0)

                        if looking_away:
                            events.append(
                                ProctoringEvent(
                                    session_id=self.session_id,
                                    timestamp=timestamp,
                                    event_type="LOOKING_AWAY",
                                    severity="medium",
                                    confidence=float(confidence),
                                    message="Candidate appears to be looking away",
                                    metadata={
                                        "gaze_direction": gaze_direction
                                    },
                                )
                            )

            except AttributeError:
                pass

            # ---------------------------------------------------------
            # 4. MOUTH DETECTION
            # ---------------------------------------------------------

            try:
                mouth_result = self.mouth_monitor.process(frame)

                if mouth_result is not None:
                    if isinstance(mouth_result, dict):
                        talking = mouth_result.get(
                            "talking",
                            mouth_result.get("mouth_open", False),
                        )

                        confidence = mouth_result.get("confidence", 1.0)

                        if talking:
                            events.append(
                                ProctoringEvent(
                                    session_id=self.session_id,
                                    timestamp=timestamp,
                                    event_type="MOUTH_ACTIVITY",
                                    severity="medium",
                                    confidence=float(confidence),
                                    message="Mouth activity detected",
                                    metadata={
                                        "talking": True,
                                    },
                                )
                            )

            except AttributeError:
                pass

            # ---------------------------------------------------------
            # 5. OBJECT DETECTION
            # ---------------------------------------------------------

            try:
                object_result = self.object_detector.detect(frame)

                if object_result is not None:
                    detected_objects = []

                    if isinstance(object_result, dict):
                        detected_objects = object_result.get(
                            "objects",
                            [],
                        )

                    elif isinstance(object_result, (list, tuple)):
                        detected_objects = list(object_result)

                    if detected_objects:
                        events.append(
                            ProctoringEvent(
                                session_id=self.session_id,
                                timestamp=timestamp,
                                event_type="SUSPICIOUS_OBJECT",
                                severity="high",
                                confidence=1.0,
                                message="Potentially suspicious object detected",
                                metadata={
                                    "objects": detected_objects,
                                },
                            )
                        )

            except AttributeError:
                pass

        except Exception as exc:
            # Never allow a single bad frame to crash the entire
            # FastAPI/WebSocket proctoring session.
            print(
                f"[DetectionAdapter] Error processing frame "
                f"for session {self.session_id}: {exc}"
            )

            traceback.print_exc()

            events.append(
                ProctoringEvent(
                    session_id=self.session_id,
                    timestamp=datetime.now(timezone.utc).isoformat(),
                    event_type="DETECTION_ERROR",
                    severity="high",
                    confidence=0.0,
                    message="An error occurred while processing the frame",
                    metadata={
                        "error": str(exc),
                    },
                )
            )

        return events

    def decode_frame(self, frame_data: bytes) -> Optional[np.ndarray]:
        """
        Decode a binary JPEG/WebP frame received over WebSocket.

        Returns:
            OpenCV BGR frame or None if decoding fails.
        """

        try:
            if not frame_data:
                return None

            np_data = np.frombuffer(frame_data, dtype=np.uint8)

            if np_data.size == 0:
                return None

            frame = cv2.imdecode(np_data, cv2.IMREAD_COLOR)

            if frame is None:
                raise ValueError("OpenCV could not decode the received image")

            return frame

        except Exception as exc:
            print(
                f"[DetectionAdapter] Frame decoding error "
                f"for session {self.session_id}: {exc}"
            )

            return None

    def process_binary_frame(
        self,
        frame_data: bytes,
    ) -> List[ProctoringEvent]:
        """
        Decode a binary WebSocket image and run detection.
        """

        frame = self.decode_frame(frame_data)

        if frame is None:
            return []

        return self.process_frame(frame)

    def cleanup(self) -> None:
        """
        Release resources owned by the detection adapter.
        """

        if self._closed:
            return

        self._closed = True

        detectors = [
            self.face_detector,
            self.eye_tracker,
            self.mouth_monitor,
            self.multi_face_detector,
            self.object_detector,
        ]

        for detector in detectors:
            try:
                if detector is None:
                    continue

                # Support detectors that expose either close()
                # or cleanup().
                if hasattr(detector, "cleanup"):
                    detector.cleanup()

                elif hasattr(detector, "close"):
                    detector.close()

            except Exception as exc:
                print(
                    f"[DetectionAdapter] Error cleaning up "
                    f"{type(detector).__name__}: {exc}"
                )

    def close(self) -> None:
        """Alias for cleanup()."""
        self.cleanup()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback_value):
        self.cleanup()